### PR TITLE
Fix window scrolling after rustfmt is run

### PR DESCRIPTION
**Pull request by apiraino**
Hello,

I tried investigating the window scrolling after rustfmt is run (this issue has been referenced in various forms in issues #268 #231 #251) as I am still experiencing it and imo it's pretty annoying.

I'm not an elisp expert, but I think a quick fix/workaround could be to simply nail the window start position and restore it after rustfmt has finished.

I think there may be still cases where the code reformatting can be a bit confusing (f.e. `rustfmt`'ing a big messed up file), but at least I'm not getting mad every time I compulsively save a buffer :-)

Can you let me know what you think of this little patch? I tested it a bit and it has greatly improved my coding experience with rustfmt.

Thanks for your time!

EDIT: I did some checks, but I'm not sure how to fix those warning that make the CI fail
EDIT2: maybe fixed (not sure if fix is correct though)

### CODE REVIEW

**Comment by jjwest** [comment]
Works nicely for me. I'd suggest using a let binding instead of defvar, which creates a persistent global variable:

    (let ((w-start (window-start)))
     .....
    )

**Comment by apiraino** [comment]
@jjwest thanks, appreciated! I've pushed a patch to reflect your suggestion.

**Comment by Dushistov** [comment]
Issue #256 looks like also related

**Comment by drrlvn** [comment]
Isn't this is the reason that `save-excursion` exists? I think it should be possible to just use:

```elisp
(save-excursion
    (rust--format-call (current-buffer)))
```

**Comment by sebastiencs** [comment]
@drrlvn `save-excursion` uses markers that might be deleted by `rust--format-call`, see https://emacs.stackexchange.com/a/7577/15635

**Comment by drrlvn** [comment]
@sebastiencs I see.

I tried looking at how `clang-format` does this as I've not had this issue in C++ code and it looks like the cursor position is passed as an argument and then the json output contains the location the cursor should be moved to. See [the source](https://github.com/sonatard/clang-format/blob/57a638fa6684fa036bbc83dfd845171b8aef7001/clang-format.el#L54).

Is there such an option in `rustfmt`, and if not would it maybe be possible to add it? I imagine every editor would need something like this.

**Comment by apiraino** [comment]
review @nikomatsakis? anyone? suggestions?

thanks

**Comment by brotzeit** [comment]
FYI it seems I was able to fix this issue by not using stdin in the `before-save-hook`. Since the buffer gets saved anyway it's no problem to run rustfmt on the files and revert the buffers afterwards. I think this should also work for `rust-mode`, but I'm not sure.

**Comment by nikomatsakis** [comment]
This looks like a pretty simple patch :)

**Comment by apiraino** [comment]
@nikomatsakis I'm sorry I had lost track of this issue :-) you mean this patch can be pushed forward? I think I've been using it since.

**Comment by pnkfelix** [comment]
Ill try to take a look at this this week. 

It would be interesting to try to figure out how to make a regression test for this ...

**Comment by nikomatsakis** [comment]
@apiraino seems ok to me to merge in this case. I don't really know how to judge if it will work, but I take your word for it. =) Would of course be nice to have a test, as @pnkfelix says.

**Comment by apiraino** [comment]
@nikomatsakis thanks for having a look at this patch. I can verify the effect of the patch on a sample Rust source file. However I'm afraid I can't provide an elisp test because my knowledge on that is pretty limited. If anyone is willing to help, I'd be really happy to provide a test case for the regression.

In any case here's how to reproduce:
1) Ensure you have installed `rust-mode` from melpa (currently `rust-mode-20181008.1628.el`)
2) Download this [gist](https://gist.github.com/apiraino/aadb133a9d321d06fc14abff012b0a7f)
3) Open the downloaded file in emacs
4) Follow the instructions in the Rust test file
5) You should experience that the buffer moves at the end of the current window

With my patch step (5) does not happen

Hope this helps

**Comment by brotzeit** [comment]
@apiraino You have to install rust and rustfmt in the travis config first. Then you can start with a simple test that formats a buffer. Afterwards you can write the regression test with `save-some-buffers`.

**Comment by apiraino** [comment]
@brotzeit sorry for the long hiatus, got a lot going on.

So, I did a little reseach and tried writing a test for this PR. I believe what I need to test is the `window-start` value before and after running `rust-format-buffer`.

I tried allocating a temporary buffer as in other tests (`with-temp-buffer`) but `window-start` always return nil. I'm not sure I'm on the right path.
How should the test work in order to get meaningful values for `window-start`?

Here's a gist of what I am at this moment:
https://gist.github.com/apiraino/4c8abac8d23398b2bd6dcd5d3d54e1df

**Comment by nikomatsakis** [comment]
Sorry for long hiatus. I'm kind of overwhelmed with review requests and haven't really had time to try this out. 

Maybe @mookid or @brotzeit can review?

**Comment by mookid** [comment]
Hi @apiraino, 
Looks good.

About the test, the problem is with the `let`: 


```list

(defun rust-test-fn (code expected-result)
  (with-temp-buffer
    (rust-mode)
    (insert code)
    (message "%S" (selected-window))
    ;; check window before formatting
    (let ((w-start (window-start)))
      (message "before: %s" w-start))
    (rust-format-buffer)
    (should (equal expected-result (buffer-string)))

    ;; check window start after formatting
    (let ((w-start (window-start)))
      (message "%s" w-start))))
```

**Comment by truchi** [comment]
Hi,

Any news on this ?

Thank you !

**Comment by mookid** [comment]
Integrated, thanks. Sorry for the long delay! :)

**Pull request closed without merging**
