### PR TITLE
Bump version

### PR DESCRIPTION
**Pull request by jthemphill**
I'm still stuck on a version that's 1.5 years old!

### CODE REVIEW

**Comment by tromey** [comment]
It makes it a bit simpler to update if you aren't using MELPA.  Maybe we also need to push a tag to make melpa-stable bump?  See https://github.com/rust-lang/rust-mode/issues/87

**Comment by nikomatsakis** [comment]
So...shall we land it? :)

**Comment by 4lex1v** [comment]
Could you please tag the branch also =)?

**Comment by jthemphill** [comment]
Thanks for shipping!

**Comment by pnkfelix** [comment]
sorry for the lack of action here for months; clearly the people with all the power here haven't accepted all the associated responsibility.

**Pull request merged**
