### PR TITLE
Bump version to 1.0.6

### PR DESCRIPTION
**Pull request by psibi**

### CODE REVIEW

**Comment by PuercoPop** [comment]
> [Remove 27.2 from test matrix](https://github.com/rust-lang/rust-mode/pull/552/commits/21916acdb808e85e34aa8781ebd0113c445a250b)

@psibi does this mean pull requests removing code targeting unsupported versions are welcome?

https://github.com/rust-lang/rust-mode/blob/master/rust-rustfmt.el#L68

**Comment by psibi** [comment]
> @psibi does this mean pull requests removing code targeting unsupported versions are welcome?

It is welcome. Even better if someone is able to fix the CI issue that is happening with 27.2.

**Comment by PuercoPop** [comment]
What was the issue? It seems the logs have been deleted

https://github.com/rust-lang/rust-mode/actions/runs/9155379317/job/25167625954

**Comment by psibi** [comment]
Some issue related to nix installation of that specific Emacs.

**Pull request merged**
