### PR TITLE
Add rust-promote-module-into-dir

### LINKED ISSUE #128: command to convert `foo.rs` into `foo/mod.rs` [feature-request]
It happens to me pretty regularly that I editing `foo.rs` and then decide to "promote" this into a directory-based module, usually so I can add a `foo/test.rs`, but sometimes for other reasons. I'd love a command to do this automatically!

### PR DESCRIPTION
**Pull request by tomjakubowski**
Lacking tests and completely untested on Windows!

closes #128

### CODE REVIEW

**Comment by tomjakubowski** [comment]
cc @nikomatsakis

**Comment by tomjakubowski** [comment]
Ah, d'oh... no `file-name-base` on Emacs 23. Pushing a fix.

**Comment by nikomatsakis** [comment]
ooh, neat, I should give this a spin. I have no idea how we would test it. :)

**Comment by nikomatsakis** [comment]
OK so I tried this a few times and...it seems to work for me. :) I say let's land it! We can always fix whatever obscure bugs crop up later. Thanks!

**Pull request merged**
