### PR TITLE
Fix "-> Type" on a single line indentation

### LINKED ISSUE #8: emacs mode indentation is wrong when function return -> is on its own line
<a href="https://github.com/nikomatsakis"></img></a> **Issue by [nikomatsakis](https://github.com/nikomatsakis)**
_Wednesday Apr 16, 2014 at 19:39 GMT_

_For earlier discussion, see https://github.com/rust-lang/rust/issues/13566_

_This issue was labelled with: A-tools in the Rust repository_

----

The following code indents as shown here, which is weird:

```
pub fn from_pointer_kind(base_mutbl: MutabilityCategory,
                         ptr: PointerKind)
                         -> MutabilityCategory {
                             match ptr {
                             }
                         }
```

I expect it to be:

```
pub fn from_pointer_kind(base_mutbl: MutabilityCategory,
                         ptr: PointerKind)
                         -> MutabilityCategory {
    match ptr {
    }
}
```

### PR DESCRIPTION
**Pull request by GBGamer**
Plus a few minor spelling changes in comments

Fixes #8

### CODE REVIEW

**Comment by GBGamer** [comment]
Can I just say thank you to the people who wrote this? Incredibly well commented, easy to edit, awesomeness.

**Comment by quantheory** [comment]
Ah! This is definitely an improvement. I find that there are a *lot* of other cases where indentation is at least somewhat strange in `rust-mode`, which is perhaps an argument for switching to a more "tried and true" way of dealing with indentation, e.g. based on SMIE. (To see what I mean, find a random `if` statement with a moderately complex condition, where the `{` is after the condition rather than on a line by itself, and insert a newline between any random pair of tokens, then reindent the block. This will almost certainly mess up the indentation of the entire `if` block. Several other types of expression are similarly fragile to users adding newlines in "unexpected" places.)

Nevertheless, this PR works around one of the most common bad cases, so it is still quite helpful.

**Comment by GBGamer** [comment]
Yes, we can work on the rest of the indentation issues later, this is just an issue that I had that was an easy fix.

**Comment by GBGamer** [comment]
@quantheory I'm setting up a new repo in order to work on an SMIE grammar for Rust. Would you like to join me? (I've never done any SMIE work before (and in fact, am an Emacs newbie), so I'd like someone who actually knows what they're doing.

**Comment by quantheory** [comment]
@GBGamer I would, but I'm afraid I am really the wrong person to ask. I actually only have a dimly-remembered mental picture of how SMIE works from several years back, and I'm pretty overextended in any case. I really only check in here because I like to ~~whine~~ hope that some of the quirks in the current `rust-mode` will get ironed out soon.

**Comment by GBGamer** [comment]
Pinging @nikomatsakis

**Comment by pnkfelix** [comment]
Okay, normally I'd say "please add a test case."

But I want this badly enough that I'm probably going to just merge it.  (I just want to quickly double-check myself that it behaves as advertised -- if so, then I'll merge it and then work on a test case myself.)

**Comment by pnkfelix** [comment]
Yes, awesome, it fixes both of my most important cases:

```rust
    fn foo(a: i32)
           -> i32 {
               // whoops
           }
                                                                                
    fn foo<T>(a: i32)
              -> i32 where T:Foo {
                  // bad too
              }
```

**Comment by GBGamer** [comment]
@pnkfelix Thanks for the regression test, I didn't even think about that :stuck_out_tongue_closed_eyes:

**Pull request merged**
