### PR TITLE
CI: Support for emacs 29.3

### PR DESCRIPTION
**Pull request by psibi**

### CODE REVIEW

**Comment by psibi** [comment]
@jcs090218 Can you add support for Emacs 29.3 in jcs090218/setup-emacs ?

**Comment by jcs090218** [comment]
Windows is not up there yet. I'll update you once it's updated.

**Comment by jcs090218** [comment]
It's up!

**Comment by psibi** [comment]
@jcs090218 Thanks for the quick feature support!

**Pull request merged**
