### PR TITLE
provide alternative rust-mode that derives from rust-ts-mode

### PR DESCRIPTION
**Pull request by brotzeit**

### CODE REVIEW

**Comment by thblt** [comment]
I was just looking into a way to complement the new `rust-ts-mode` with `rust-mode` features. Wouldn't it be nicer to separate i those features as a minor mode that could be hooked to `rust-ts-mode`?

**Comment by brotzeit** [comment]
If rust-mode was a new package that's supposed to add features to rust-ts-mode it would make sense to use a minor mode. I think there is no real downside to using a derived mode and this way we don't have to apply any additional changes. We can still change this once treesitter is the standard and the old code is deprecated. For now it seems to be the more convenient solution.

But maybe I'm wrong. Other opinions ? @jimblandy @psibi

**Comment by thblt** [comment]
Ha, I see your point, and backward compatibility is indeed a nice thing :)

Maybe it would be nice if the control variable defaulted to t whenever `rust-ts-mode` is available so the transition will be perfectly transparent:

``` elisp
(defcustom rust-mode-treesitter-derive
  (and (fboundp 'treesit-language-available-p)
       (treesit-language-available-p 'rust))
…                              
```

**Comment by brotzeit** [comment]
I thought about it but the ts mode applies different syntax highlighting. Users will probably complain that we just change the default. Many rust-mode users only want very basic features. I know those people probably won't use emacs master, but I would wait.

**Comment by jimblandy** [comment]
I think we should always feel free to make substantial improvements even when they change behavior. If treesitter is available, reliable, and really provides the improvements it claims to, we should just use it.

**Comment by creese** [comment]
Can this be merged?

**Comment by uncomfyhalomacro** [comment]
hello. will this be merged or are there any more to be done first? thank you!

**Comment by psibi** [comment]
I have done a minor change to this PR to make it work for my setup (Emacs 29.1). I can confirm that it works with my basic testing. I'm planning to test drive this PR for around a week to see if I face any issues and merge it if I see no issues.

If others can test drive this PR meanwhile, that will be helpful.

**Pull request merged**
