### PR TITLE
Update rustfmt's default edition: 2018 -> 2021

### PR DESCRIPTION
**Pull request by PuercoPop**
The latest edition seems like a good default.

### CODE REVIEW

**Review by psibi — COMMENTED** [review]
Can you also update the changelog with an unreleased section?

**Comment by PuercoPop** [comment]
> Can you also update the changelog with an unreleased section?

Done

**Review by psibi — APPROVED** [review]
Thanks!

**Comment by apiraino** [comment]
For the record, this change will be neutralized in https://github.com/rust-lang/rust-mode/pull/571

I reported in https://github.com/rust-lang/rust-mode/issues/570 that rust-rustfmt-switches was shadowing the rustfmt.toml, ignoring any user configuration.

**Pull request merged**
