### PR TITLE
fix quoting in two doc strings

### PR DESCRIPTION
**Pull request by tromey**
This fixes the quotes in a couple of docstrings.

### CODE REVIEW

**Comment by steveklabnik** [comment]
So, using a backtick and a `'` is a pretty common quoting style. That doesn't mean that we shouldn't switch it, but it should also change the backticks to `'`, if we are.

**Comment by steveklabnik** [comment]
oh, i see. i read the diff wrong. sigh.

**Comment by huonw** [comment]
I'll be @bors. :smile:

**Pull request merged**
